version: "3"

services:
  web:
    # the application's web service (container) will use an image based on our Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.dev
    # map the internal port 80 to port 8000 on the host
    ports:
      - "80:80"
    # map the host directory to app (which allows us to see and edit files inside the container)
    volumes:
      - ".:/app:rw"
      
    # the default command to run whenever the container is launched
    # command: python manage.py runserver 0.0.0.0:80
    env_file: .env
