# Generated by Django 5.0.1 on 2024-01-26 12:42

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import tenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('site_name', models.CharField(max_length=50)),
                ('site_image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('type', models.CharField(choices=[('public', 'public'), ('type_sim', 'type_sim'), ('type2', 'type2')], default='public', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('theme_folder', models.CharField(default='galaxy', max_length=50)),
                ('dns_record', models.CharField(default='', max_length=50)),
                ('theme_config', models.JSONField(default=tenant.models.theme_config_default, verbose_name='ThemeConfig')),
                ('config', models.JSONField(default=tenant.models.other_config_default, verbose_name='TenantConfig')),
                ('paid_until', models.DateField(auto_now_add=True)),
                ('on_trial', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
