# Generated by Django 5.0.1 on 2024-01-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('tenant_type', models.CharField(choices=[('type_sim', 'Kinh doanh SIM số'), ('type_fengshui', 'Phong thuỷ')], max_length=40)),
                ('description', models.TextField(blank=True, max_length=170, null=True)),
                ('featured_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('publishedAt', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant Templates',
                'verbose_name_plural': 'Tenant Templates',
                'db_table': 'tenant_templates',
            },
        ),
    ]
