# Generated by Django 5.0.1 on 2024-01-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenanttemplates_delete_tenanttypes_alter_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('public', 'public'), ('type_sim', 'type_sim'), ('type_fengshui', 'type_fengshui')], default='public', max_length=100),
        ),
    ]
