# Generated by Django 5.0.1 on 2024-01-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_delete_tenanttypes_alter_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenanttemplates',
            name='tenant_type',
            field=models.CharField(choices=[], max_length=40),
        ),
    ]
