# Generated by Django 5.0.1 on 2024-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_delete_tenanttypes_alter_tenant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenanttemplates',
            name='link',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenanttemplates',
            name='theme_config_url',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
