# Generated by Django 5.0.1 on 2024-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_alter_tenanttemplates_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
