# Generated by Django 5.0.1 on 2024-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_tenant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
