# Generated by Django 5.0.1 on 2024-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_tenant_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='site_name',
            field=models.CharField(max_length=50, verbose_name='Tên site'),
        ),
    ]
