# Generated by Django 5.0.2 on 2024-02-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_alter_tenant_paid_until_alter_tenant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='service_package',
            field=models.CharField(choices=[], default='', max_length=100, verbose_name='Gói dịch vụ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[], default='', max_length=100, verbose_name='Loại hình kinh doanh'),
        ),
    ]
