# Generated by Django 5.0.2 on 2024-02-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_tenant_service_package_alter_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='service_package',
            field=models.IntegerField(choices=[(1, 'Cơ bản'), (2, 'Gói Bạc'), (3, 'Gói Kim Cương')], verbose_name='Gói dịch vụ'),
        ),
    ]
