# Generated by Django 5.0.2 on 2024-02-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_alter_tenant_service_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='service_package',
            field=models.IntegerField(choices=[(1, 'Cơ bản'), (2, 'Gói Bạc'), (3, 'Gói Kim Cương')], default=1, verbose_name='Gói dịch vụ'),
        ),
    ]
