# Generated by Django 5.0.2 on 2024-02-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_alter_tenant_service_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='site_name',
            field=models.CharField(max_length=50, verbose_name='Tên site (*)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[], default='', max_length=100, verbose_name='Loại hình kinh doanh (*)'),
        ),
    ]
