# Generated by Django 5.0.2 on 2024-03-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0014_alter_tenant_site_name_alter_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại (*)'),
        ),
    ]
