# Generated by Django 4.2.11 on 2024-05-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
