# Generated by Django 5.0.2 on 2024-02-25 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=15)),
                ('sessionId', models.CharField(blank=True, max_length=40, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=15)),
                ('sim', models.CharField(max_length=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('cif', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('source', models.CharField(blank=True, max_length=16, null=True)),
                ('session_id', models.CharField(blank=True, max_length=32, null=True)),
                ('browse_history', models.TextField(blank=True, null=True)),
                ('sim_full', models.CharField(blank=True, max_length=30, null=True)),
                ('sim_status', models.CharField(blank=True, max_length=15, null=True)),
                ('sim_info', models.TextField(blank=True, null=True)),
                ('prepay', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('packageName', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
