# Generated by Django 5.0.2 on 2024-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='Customer Id', null=True),
        ),
    ]
