# Generated by Django 5.0.2 on 2024-02-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_affiliate', '0002_alter_transaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_on_delivery',
            field=models.IntegerField(blank=True, help_text='Số tiền thanh toán còn lại', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_calc',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Gía bán sau khi áp dụng chính sach giảm giá nếu có', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prepay',
            field=models.IntegerField(blank=True, help_text='Tổng tiền thanh toán trước', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Gia gốc', max_digits=15, null=True),
        ),
    ]
