# Generated by Django 5.0.2 on 2024-02-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_affiliate', '0003_transaction_payment_on_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
