# Generated by Django 5.0.2 on 2024-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_affiliate', '0004_transaction_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
