# Generated by Django 4.2.11 on 2024-03-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_affiliate', '0005_transaction_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
