from django.apps import AppConfig

class SimsConfig(AppConfig):

    default_auto_field = 'django.db.models.BigAutoField'
    name = 'sims'
    verbose_name = 'Quản Lý Sim'
    depends_on = ['blog']
    def ready(self):
        from . import signals

    filterTypes = [
    {
        "label": "4444",
        "title": "Sim Tứ Quý",
        "name": "Sim Tứ Quý",
        "c": "68",
        "link": "/sim-tu-quy",
        "showCat": [],
        "notFilterItem": ['types'],
    },
    {
        "name": "333",
        "title": "Sim Tam Hoa",
        "label": "333",
        "c": "80",
        "link": "/sim-tam-hoa",
        "notFilterItem": ['types'],
    },
    {
        "label": "AABBCC",
        "title": "Sim Dễ Nhớ",
        "name": "Sim Dễ Nhớ",
        "c": "76",
        "link": "/sim-de-nho",
        "notFilterItem": ['types'],
    },
    {
        "label": "AA.BB",
        "title": "Sim Lặp Kép",
        "name": "Sim Lặp Kép",
        "c": "67",
        "link": "/sim-lap-kep",
        "notFilterItem": ['types'],
        "showCat":["/sim-lap", "/sim-kep", "/sim-kep-2", "/sim-kep-3", "/sim-kep-4", "/sim-lap-2", "/sim-lap-3", "/sim-lap-4"],
    },
    {
        "label": "AB.AB",
        "title": "Sim Lặp",
        "name": "Sim Lặp",
        "c": "123",
        "link": "/sim-lap",
        "notFilterItem": ['types'],
        "showCat":["/sim-lap-2", "/sim-lap-3", "/sim-lap-4"],
    },
    {
        "label": "AB.BA",
        "title": "Sim Gánh Đảo",
        "name": "Sim Gánh Đảo",
        "c": "79",
        "link": "/sim-ganh-dao",
        "notFilterItem": ['types'],
    },
    {
        "label": "6789",
        "title": "Sim Tiến Lên",
        "name": "Sim Tiến Lên",
        "c": "81",
        "link": "/sim-tien-len",
        "notFilterItem": ['types'],
        "showCat":["/sim-tien-3", "/sim-tien-4", "/sim-tien-5"],
    },
    {
        "label": "ABC.ABC",
        "title": "Sim Taxi",
        "name": "Sim Taxi",
        "c": "74",
        "link": "/sim-taxi",
        "notFilterItem": ['types'],
        "showCat":["/sim-taxi-2", "/sim-taxi-3", "/sim-taxi-4"],

    },
    {
        "label": "75.78.78",
        "title": "Sim Số Độc",
        "name": "Sim Số Độc",
        "c": "78",
        "notFilterItem": ['types'],
        "link": "/sim-so-doc",
    },
    {
        "label": "09x",
        "title": "Sim Đầu Số Cổ",
        "c": "106",
        "link": "/sim-dau-so-co",
        "notFilterItem": ['types'],
    },
    {
            "label": "VIP",
            "title": "Sim VIP",
            "name": "Sim VIP",
            "c": "82",
            "link": "/sim-vip",
            "notFilterItem": ['types'],
        },
        {
            "label": "666.666",
            "title": "Sim Lục Quý",
            "name": "Sim Lục Quý",
            "c": "100",
            "link": "/sim-luc-quy",
            "notFilterItem": ['types'],
        },
        {
            "label": "55555",
            "name": "Sim Ngũ Quý",
            "title": "Sim Ngũ Quý",
            "c": "99",
            "link": "/sim-ngu-quy",
            "notFilterItem": ['types'],
        },
        {
            "label": "199x",
            "name": "Sim Năm Sinh",
            "title": "Sim Năm Sinh",
            "c": '77',
            "title_seo": "Sim Năm Sinh",
            "link": "/sim-nam-sinh",
            "notFilterItem": ['types']
        },
        {
            "label": "38.78",
            "name": "Sim Ông Địa",
            "title": "Sim Ông Địa",
            "c": '70',
            "link": "/sim-ong-dia",
            "notFilterItem": ['types'],
        },
        {
            "label": "68.68",
            "name": "Sim Lộc Phát",
            "title": "Sim Lộc Phát",
            "c": '73',
            "link": "/sim-loc-phat",
            "notFilterItem": ['types'],
        },
        {
            "label": "39.79",
            "name": "Sim Thần Tài",
            "title": "Sim Thần Tài",
            "c": '72',
            "link": "/sim-than-tai",
            "notFilterItem": ['types'],
        },
        {
            "label": "xx88",
            "name": "Sim Đại Cát",
            "title": "Sim Đại Cát",
            "c": '115',
            "link": "/sim-dai-cat",
            "notFilterItem": ['types'],
        },
        {
            "label": "xx",
            "name": "Sim Trả Góp",
            "title": "Sim Trả Góp",
            "c": '200',
            "link": "/sim-tra-gop",
            "notFilterItem": ['types'],
        },
    ]
    filterPrice = [
    {
        "name": "< 500 K",
        "title": "Sim Giá < 500 Nghìn",
        "label": "Sim Giá < 500 Nghìn",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-duoi-500-nghin",
        "pr": "0-500000"
    },
    {
        "name": "500 - 1 Tr",
        "title": "Sim Giá 500 - 1 Triệu",
        "label": "Sim Giá 500 - 1 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-500-nghin-den-1-trieu",
        "pr": "500000-1000000",
    },
    {
        "name": "1 - 3 Tr",
        "title": "Sim Giá 1 - 3 Triệu",
        "label": "Sim Giá 1 - 3 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-1-trieu-den-3-trieu",
        "pr": "1000000-3000000",
    },
    {
        "name": "3 - 5 Tr",
        "title": "Sim Giá 3 - 5 Triệu",
        "label": "Sim Giá 3 - 5 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-3-trieu-den-5-trieu",
        "pr": "3000000-5000000",
    },
    {
        "name": "5 - 10 Tr",
        "title": "Sim Giá 5 - 10 Triệu",
        "label": "Sim Giá 5 - 10 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-5-trieu-den-10-trieu",
        "pr": "5000000-10000000"
    },
    {
        "name": "10 - 30 Tr",
        "title": "Sim Giá 10 - 30 Triệu",
        "label": "Sim Giá 10 - 30 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-10-trieu-den-30-trieu",
        "pr": "10000000-30000000",
    },
    {
        "name": "30 - 50 Tr",
        "title": "Sim Giá 30 - 50 Triệu",
        "label": "Sim Giá 30 - 50 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-30-trieu-den-50-trieu",
        "pr": "30000000-50000000",
    },
    {
        "name": "50 - 80 Tr",
        "title": "Sim Giá 50 - 80 Triệu",
        "label": "Sim Giá 50 - 80 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-50-trieu-den-80-trieu",
        "pr": "50000000-80000000",
    },
    {
        "name": "80 - 100 Tr",
        "title": "Sim Giá 80 - 100 Triệu",
        "label": "Sim Giá 80 - 100 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-80-trieu-den-100-trieu",
        "pr": "80000000-100000000",
    },
    {
        "name": "100 - 150 Tr",
        "title": "Sim Giá 100 - 150 Triệu",
        "label": "Sim Giá 100 - 150 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-100-trieu-den-150-trieu",
        "pr": "100000000-150000000",
    },
    {
        "name": "150 - 200 Tr",
        "title": "Sim Giá 150 - 200 Triệu",
        "label": "Sim Giá 150 - 200 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-150-trieu-den-200-trieu",
        "pr": "150000000-200000000",
    },
    {
        "name": "200 - 300 Tr",
        "title": "Sim Giá 200 - 300 Triệu",
        "label": "Sim Giá 200 - 300 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-200-trieu-den-300-trieu",
        "pr": "200000000-300000000",
    },
    {
        "name": "300 - 500 Tr",
        "title": "Sim Giá 300 - 500 Triệu",
        "label": "Sim Giá 300 - 500 Triệu",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-300-trieu-den-500-trieu",
        "pr": "300000000-500000000",
    },
    {
        "name": "500 - 1 Tỷ",
        "title": "Sim Giá 500 - 1 Tỷ",
        "label": "Sim Giá 500 - 1 Tỷ",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-tu-500-trieu-den-1-ti",
        "pr": "500000000-1000000000",
    },
    {
        "name": "> 1 Tỷ",
        "title": "Sim Giá Trên 1 Tỷ",
        "label": "Sim Giá Trên 1 Tỷ",
        "notFilterItem": ['prices'],
        "link": "/sim-gia-so-dep-lon-hon-1-ti",
        "pr": "1000000000-10000000000000",
    },
    ]
    filterTel = [
        {
            "key": "viettel",
            "telco": "viettel",
            "name": "Viettel",
            "title": "Sim Viettel",
            "label": "Sim Viettel",
            "logo": "/static/{theme_folder}/images/logoTel/viettel.svg",
            "link": "/sim-viettel",
            "notFilterItem": ['telco'],
            "t": "1",
            "heads": [
            "032",
            "033",
            "034",
            "035",
            "036",
            "037",
            "038",
            "039",
            "096",
            "097",
            "098",
            "086",
            ],
        },
        {
            "key": "vinaphone",
            "telco": "vinaphone",
            "name": "Vinaphone",
            "title": "Sim Vinaphone",
            "label": "Sim Vinaphone",
            "logo": "/static/{theme_folder}/images/logoTel/vinaphone.svg",
            "link": "/sim-vinaphone",
            "notFilterItem": ['telco'],
            "t": "2",
            "heads": ["083", "084", "085", "081", "082", "088", "091", "094"],
        },
        {
            "key": "mobifone",
            "telco": "mobifone",
            "name": "Mobifone",
            "title": "Sim Mobifone",
            "label": "Sim Mobifone",
            "logo": "/static/{theme_folder}/images/logoTel/mobifone.svg",
            "link": "/sim-mobifone",
            "notFilterItem": ['telco'],
            "t": "3",
            "heads": ["070", "076", "077", "078", "079", "089", "090", "093"],
        },
        {
            "key": "vietnammobile",
            "telco": "vietnamobile",
            "name": "Vietnammobile",
            "title": "Sim Vietnammobile",
            "label": "Sim Vietnammobile",
            "logo": "/static/{theme_folder}/images/logoTel/vietnammobile.svg",
            "link": "/sim-vietnamobile",
            "notFilterItem": ['telco'],
            "t": "4",
            "heads": ["056", "058", "092"],
        },
        {
            "key": "gmobile",
            "telco": "gmobile",
            "name": "G-mobile",
            "title": "Sim G-mobile",
            "label": "Sim G-mobile",
            "logo": "/static/{theme_folder}/images/logoTel/gmobile.svg",
            "notFilterItem": ['telco'],
            "link": "/sim-gmobile",
            "t": "5",
            "heads": ["059", "099"],
        },
        {
            "key": "mayban",
            "telco": "mayban",
            "name": "mayban",
            "title": "Sim mạng cố định",
            "label": "Sim mạng cố định",
            "logo": "/static/{theme_folder}/images/logoTel/mayban.svg",
            "notFilterItem": ['telco'],
            "link": "/sim-mayban",
            "t": "7",
            "heads": [
                "0212", "0213", "0214", "0215", "0216", "0218", "0203", "0204", "0205", "0206", "0207", "0208", "0209", "0210", "0211",
                "0219", "0220", "0221", "0222", "024", "0225", "0226", "0227", "0228", "0229", "0232", "0233", "0234", "0235", "0236",
                "0237", "0238", "0239", "0251", "0252", "0254", "0255", "0256", "0257", "0258", "0259", "0260", "0261", "0262", "0263",
                "0269", "028", "0270", "0271", "0272", "0273", "0274", "0275", "0276", "0277", "0290", "0291", "0292", "0294", "0296",
                "0297", "0299"
            ],
        },
        {
            "key": "itelecom",
            "telco": "itelecom",
            "name": "Itel",
            "title": "Sim Itel",
            "label": "Sim Itel",
            "logo": "/static/{theme_folder}/images/logoTel/itel.svg",
            "link": "/sim-itelecom",
            "notFilterItem": ['telco'],
            "t": "8",
            "heads": ["087"],
        },
        # {
        #     "key": "itel telecom",
        #     "telco": "itel telecom",
        #     "name": "Itel",
        #     "title": "Sim Itel",
        #     "label": "Sim Itel",
        #     "logo": "/static/{theme_folder}/images/logoTel/itel.svg",
        #     "link": "/sim-itelecom",
        #     "notFilterItem": ['telco'],
        #     "t": "8",
        #     "heads": ["087"],
        # },
    ]
    filterHead = [
        {
            "name": "09x",
            "h": "09",
            "title": "Sim Đầu Số 09",
            "label": "Sim Đầu Số 09",
            "notFilterItem": ['head'],
            "link": "/sim-dau-so-09",
        },
        {
            "name": "08x",
            "h": "08",
            "title": "Sim Đầu Số 08",
            "label": "Sim Đầu Số 08",
            "notFilterItem": ['head'],
            "link": "/sim-dau-so-08",
        },
        {
            "name": "07x",
            "h": "07",
            "title": "Sim Đầu Số 07",
            "label": "Sim Đầu Số 07",
            "notFilterItem": ['head'],
            "link": "/sim-dau-so-07",
        },
        {
            "name": "05x",
            "h": "05",
            "title": "Sim Đầu Số 05",
            "label": "Sim Đầu Số 05",
            "notFilterItem": ['head'],
            "link": "/sim-dau-so-05",
        },
        {
            "name": "03x",
            "h": "03",
            "title": "Sim Đầu Số 03",
            "label": "Sim Đầu Số 03",
            "notFilterItem": ['head'],
            "link": "/sim-dau-so-03",
        },
        {
            "name": "",
            "h": "",
            "title": "Sim Đầu Số",
            "label": "Sim Đầu Số",
            "notFilterItem": ['head'],
            "link": "/sim-dau-so",
            "hide": 1
        },
    ]
    filterFates = [
        {
            "cf": "114",
            "name": "Kim",
            "title": "Sim Mệnh Kim",
            "label": "Sim Mệnh Kim",
            "logo": "/static/{theme_folder}/images/sidebar/logo_kim.svg",
            "link": "/sim-hop-menh-kim",
            "showCat": [],
            "notFilterItem": ['types'],
        },
        {
            "cf": "112",
            "name": "Mộc",
            "title": "Sim Mệnh Mộc",
            "label": "Sim Mệnh Mộc",
            "logo": "/static/{theme_folder}/images/sidebar/logo_moc.svg",
            "link": "/sim-hop-menh-moc",
            "showCat": [],
            "notFilterItem": ['types'],
        },
        {
            "cf": "110",
            "name": "Thuỷ",
            "title": "Sim Mệnh Thuỷ",
            "label": "Sim Mệnh Thủy",
            "logo": "/static/{theme_folder}/images/sidebar/logo_thuy.svg",
            "link": "/sim-hop-menh-thuy",
            "showCat": [],
            "notFilterItem": ['types'],

        },
        {
            "cf": "111",
            "name": "Hoả",
            "title": "Sim Mệnh Hoả",
            "label": "Sim Mệnh Hỏa",
            "logo": "/static/{theme_folder}/images/sidebar/logo_hoa.svg",
            "link": "/sim-hop-menh-hoa",
            "showCat": [],
            "notFilterItem": ['types'],
        },
        {
            "cf": "113",
            "name": "Thổ",
            "title": "Sim Mệnh Thổ",
            "label": "Sim Mệnh Thổ",
            "logo": "/static/{theme_folder}/images/sidebar/logo_tho.svg",
            "link": "/sim-hop-menh-tho",
            "showCat": [],
            "notFilterItem": ['types'],
        },
    ]
    filterPopularKeyword = [
        
        {
            "name": "Sim Tứ Quý 9",
            "title": "Sim Tứ Quý 9",
            "label": "Sim Tứ Quý 9",
            "c": "68",
            "tail": '9999',
            "link": "/sim-tu-quy-9999",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tam Hoa 0",
            "title": "Sim Tam Hoa 0",
            "label": "Sim Tam Hoa 0",
            "c": "80",
            "tail": '000',
            "link": "/sim-tam-hoa-000",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
        {
            "name": "Sim Tam Hoa 5",
            "title": "Sim Tam Hoa 5",
            "label": "Sim Tam Hoa 5",
            "c": "80",
            "tail": '555',
            "link": "/sim-tam-hoa-555",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
        {
            "name": "Sim Tứ Quý 0",
            "title": "Sim Tứ Quý 0",
            "label": "Sim Tứ Quý 0",
            "c": "68",
            "tail": '0000',
            "link": "/sim-tu-quy-0000",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tam Hoa 1",
            "title": "Sim Tam Hoa 1",
            "label": "Sim Tam Hoa 1",
            "c": "80",
            "tail": '111',
            "link": "/sim-tam-hoa-111",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
        {
            "name": "Sim Tam Hoa 2",
            "title": "Sim Tam Hoa 2",
            "label": "Sim Tam Hoa 2",
            "c": "80",
            "tail": "222",
            "link": "/sim-tam-hoa-222",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
        {
            "name": "Sim Tam Hoa 3",
            "title": "Sim Tam Hoa 3",
            "label": "Sim Tam Hoa 3",
            "c": "80",
            "tail": '333',
            "link": "/sim-tam-hoa-333",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
        {
            "name": "Sim Tứ Quý 8",
            "title": "Sim Tứ Quý 8",
            "label": "Sim Tứ Quý 8",
            "c": "68",
            "tail": "8888",
            "link": "/sim-tu-quy-8888",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tam Hoa 4",
            "title": "Sim Tam Hoa 4",
            "label": "Sim Tam Hoa 4",
            "c": "80",
            "tail": '444',
            "link": "/sim-tam-hoa-444",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
        {
            "name": "Sim Tam Hoa 7",
            "title": "Sim Tam Hoa 7",
            "label": "Sim Tam Hoa 7",
            "c": "80",
            "tail": "777",
            "link": "/sim-tam-hoa-777",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
        {
            "name": "Sim Tứ Quý 1",
            "title": "Sim Tứ Quý 1",
            "label": "Sim Tứ Quý 1",
            "c": "68",
            "tail": '1111',
            "link": "/sim-tu-quy-1111",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tứ Quý 7",
            "title": "Sim Tứ Quý 7",
            "label": "Sim Tứ Quý 7",
            "c": "68",
            "tail": "7777",
            "link": "/sim-tu-quy-7777",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tam Hoa 9",
            "title": "Sim Tam Hoa 9",
            "label": "Sim Tam Hoa 9",
            "c": "80",
            "tail": "999",
            "link": "/sim-tam-hoa-999",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
        {
            "name": "Sim Tứ Quý 2",
            "title": "Sim Tứ Quý 2",
            "label": "Sim Tứ Quý 2",
            "c": "68",
            "tail": '2222',
            "link": "/sim-tu-quy-2222",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tứ Quý 6",
            "title": "Sim Tứ Quý 6",
            "label": "Sim Tứ Quý 6",
            "c": "68",
            "tail": "6666",
            "link": "/sim-tu-quy-6666",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tứ Quý 3",
            "title": "Sim Tứ Quý 3",
            "label": "Sim Tứ Quý 3",
            "c": "68",
            "tail": "3333",
            "link": "/sim-tu-quy-3333",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tứ Quý 5",
            "title": "Sim Tứ Quý 5",
            "label": "Sim Tứ Quý 5",
            "c": "68",
            "tail": "5555",
            "link": "/sim-tu-quy-5555",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tam Hoa 8",
            "title": "Sim Tam Hoa 8",
            "label": "Sim Tam Hoa 8",
            "c": "80",
            "tail": "888",
            "link": "/sim-tam-hoa-888",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
        {
            "name": "Sim Tứ Quý 4",
            "title": "Sim Tứ Quý 4",
            "label": "Sim Tứ Quý 4",
            "c": "68",
            "tail": '4444',
            "link": "/sim-tu-quy-4444",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
        },
        {
            "name": "Sim Tam Hoa 6",
            "title": "Sim Tam Hoa 6",
            "label": "Sim Tam Hoa 6",
            "c": "80",
            "tail": "666",
            "link": "/sim-tam-hoa-666",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
        },
    ]
    filterYearBirth = [
        {
            "name": "Sim Năm Sinh Viettel",
            "title": "Sim Năm Sinh Viettel",
            "label": "Sim Năm Sinh Viettel",
            "link": "/sim-nam-sinh-viettel",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-nam-sinh-viettel">Sim Năm Sinh Viettel</a>']
        },
        {
            "name": "Sim Năm Sinh Vinaphone",
            "title": "Sim Năm Sinh Vinaphone",
            "label": "Sim Năm Sinh Vinaphone",
            "link": "/sim-nam-sinh-vinaphone",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-nam-sinh-vinaphone">Sim Năm Sinh Vinaphone</a>']
        },
        {
            "name": "Sim Năm Sinh Mobifone",
            "title": "Sim Năm Sinh Mobifone",
            "label": "Sim Năm Sinh Mobifone",
            "link": "/sim-nam-sinh-mobifone",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-nam-sinh-mobifone">Sim Năm Sinh Mobifone</a>']
        },
        {
            "name": "Sim Năm Sinh Vietnamobile",
            "title": "Sim Năm Sinh Vietnamobile",
            "label": "Sim Năm Sinh Vietnamobile",
            "link": "/sim-nam-sinh-vietnamobile",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-nam-sinh-vietnamobile">Sim Năm Sinh Vietnamobile</a>']
        },
        {
            "name": "Sim Năm Sinh Gmobile",
            "title": "Sim Năm Sinh Gmobile",
            "label": "Sim Năm Sinh Gmobile",
            "link": "/sim-nam-sinh-gmobile",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-nam-sinh-gmobile">Sim Năm Sinh Gmobile</a>']
        },
        {
            "name": "Sim Năm Sinh Itelecom",
            "title": "Sim Năm Sinh Itelecom",
            "label": "Sim Năm Sinh Itelecom",
            "link": "/sim-nam-sinh-itelecom",
            "notFilterItem": ['types'],
            "breadcrumb": ['<a href="/sim-nam-sinh-itelecom">Sim Năm Sinh Itelecom</a>']
        }
    ]