# Generated by Django 4.2.8 on 2023-12-19 06:36

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('bio', models.TextField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publishedAt')),
                ('featured', models.BooleanField(default=False)),
                ('excerpt', models.CharField(blank=True, max_length=1000, null=True)),
                ('featured_image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='article')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Post'), (2, 'Page')], db_column='type', default=1, verbose_name='Type')),
                ('publishedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], db_column='status', default=1, verbose_name='Status')),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=170)),
                ('meta_keywords', models.CharField(max_length=170)),
                ('meta_canonical', models.CharField(max_length=200)),
                ('headscript', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.profile')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'ordering': ('-publishedAt',),
            },
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.article',),
        ),
    ]
