# Generated by Django 4.2.8 on 2023-12-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headscript',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_canonical',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
