# Generated by Django 4.2.8 on 2024-01-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_headscript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
