# Generated by Django 4.2.8 on 2024-01-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_related_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='footerScript',
            field=models.TextField(blank=True),
        ),
    ]
