# Generated by Django 4.2.8 on 2024-01-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_first_name_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], db_column='status', default=2, verbose_name='Status'),
        ),
    ]
