# Generated by Django 5.0.1 on 2024-02-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_sims_query_adv_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='store_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
