# Generated by Django 5.0.1 on 2024-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_sims_query_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='store_config',
            field=models.JSONField(blank=True, help_text='field for sim page adv query', null=True),
        ),
    ]
