# Generated by Django 5.0.2 on 2024-02-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_delete_articlepage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='blog_article',
        ),
    ]
