# Generated by Django 4.2.11 on 2024-03-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
