# Generated by Django 4.2.11 on 2024-04-12 14:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_category_options_alter_article_publishedat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'danh mục', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nội dung (Body)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='blog.category', verbose_name='Danh mục (Category)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Mô tả ngắn (Excerpt)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Nổi bật (Featured)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='article', verbose_name='Hình ảnh nổi bật (Featured image)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headscript',
            field=models.TextField(blank=True, null=True, verbose_name='Script đầu SEO (Headscript)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_canonical',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Canonical SEO (SEO canonical)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Mô tả SEO (SEO description)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=170, null=True, verbose_name='Từ khóa SEO (SEO keywords)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề SEO (SEO title)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo (PublishedAt)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='related_pages',
            field=models.TextField(blank=True, help_text='(Có thể nhập nhiều related pages, mỗi related pages cách nhau bởi một lần xuống dòng. Cú pháp: Tiêu đề|Link)', null=True, verbose_name='Các trang liên quan'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ẩn'), (2, 'Hiển thị')], db_column='status', default=2, verbose_name='Trạng thái (Status)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề (Title)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, max_length=170, null=True, verbose_name='Mô tả Meta'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category', verbose_name='Danh mục cha'),
        ),
    ]
