# Generated by Django 4.2.11 on 2024-04-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_category_options_alter_article_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publishedAt',), 'verbose_name': 'bài viết'},
        ),
    ]
