# Generated by Django 5.0.1 on 2024-01-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme_config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
