# Generated by Django 5.0.2 on 2024-03-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme_config', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleAlert',
        ),
    ]
