# Generated by Django 5.0.1 on 2024-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salealert',
            name='vitual_names',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salealert',
            name='vitual_sims',
            field=models.CharField(max_length=20),
        ),
    ]
