# Generated by Django 5.0.2 on 2024-02-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_alert', '0002_alter_salealert_vitual_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salealert',
            name='vitual_times',
            field=models.CharField(max_length=20),
        ),
    ]
