# Generated by Django 5.0.2 on 2024-02-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_alert', '0003_alter_salealert_vitual_times'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleAlert',
        ),
    ]
