# Generated by Django 4.2.11 on 2024-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale_alert', '0004_delete_salealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitual_names', models.CharField(max_length=100)),
                ('vitual_address', models.TextField()),
                ('vitual_sims', models.CharField(max_length=20)),
                ('vitual_times', models.CharField(max_length=20)),
            ],
        ),
    ]
