# Generated by Django 5.0.1 on 2024-02-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seo',
            new_name='SeoFile',
        ),
        migrations.RenameField(
            model_name='seofile',
            old_name='title',
            new_name='name',
        ),
    ]
