# Generated by Django 5.0.1 on 2024-02-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_optimizer', '0002_rename_seo_seofile_rename_title_seofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seofile',
            name='content',
            field=models.TextField(),
        ),
    ]
