# Generated by Django 5.0.1 on 2024-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_optimizer', '0003_alter_seofile_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c2', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('h1', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
