# Generated by Django 5.0.2 on 2024-02-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_delete_articlepage'),
        ('seo_optimizer', '0009_alter_seoproduct_max_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.article',),
        ),
    ]
