# Generated by Django 4.2.11 on 2024-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_optimizer', '0010_articlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seofile',
            name='content',
            field=models.TextField(verbose_name=' Nội dung'),
        ),
        migrations.AlterField(
            model_name='seofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên file'),
        ),
        migrations.AlterField(
            model_name='seoproduct',
            name='c2',
            field=models.IntegerField(choices=[(67, 'Sim Lặp kép'), (68, 'Sim Tứ quý'), (70, 'Sim Ông địa'), (71, 'Sim Đôi'), (72, 'Sim Thần tài'), (73, 'Sim Lộc phát'), (74, 'Sim Taxi'), (76, 'Sim Dễ nhớ'), (77, 'Sim Năm sinh'), (78, 'Sim Số độc'), (79, 'Sim Gánh đảo'), (80, 'Sim Tam hoa'), (81, 'Sim Tiến lên'), (82, 'Sim VIP'), (84, 'Sim tự chọn'), (86, 'Số máy bàn'), (99, 'Sim Ngũ Quý'), (100, 'Sim Lục Quý'), (102, 'Tam hoa kép'), (103, 'Sim Tứ Quý Giữa'), (104, 'Sim Ngũ Quý Giữa'), (105, 'Sim Lục Quý Giữa'), (106, 'Sim Đầu cổ'), (110, 'Sim hợp mệnh Thủy'), (111, 'Sim hợp mệnh Hỏa'), (112, 'Sim hợp mệnh Mộc'), (113, 'Sim hợp mệnh Thổ'), (114, 'Sim hợp mệnh Kim'), (115, 'Sim Đại Cát'), (116, 'Sim Cát'), (117, 'Sim Bình'), (118, 'Sim Hung'), (119, 'Sim Đại Hung'), (120, 'Sim Kép'), (121, 'Sim Kép 3'), (122, 'Sim Kép 4'), (123, 'Sim Lặp'), (124, 'Sim Lặp 3'), (125, 'Sim Lặp 4'), (126, 'Sim Taxi Lặp 3'), (127, 'Sim Taxi Lặp 2'), (128, 'Sim Taxi Lặp 4'), (200, 'Sim trả góp')], verbose_name='Loại sim'),
        ),
        migrations.AlterField(
            model_name='seoproduct',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='seoproduct',
            name='h1',
            field=models.CharField(max_length=200, verbose_name='Thẻ H1'),
        ),
        migrations.AlterField(
            model_name='seoproduct',
            name='max_price',
            field=models.DecimalField(blank=True, choices=[(500000, '500.000'), (1000000, '1.000.000'), (3000000, '3.000.000'), (5000000, '5.000.000'), (10000000, '10.000.000'), (30000000, '30.000.000'), (50000000, '50.000.000'), (80000000, '80.000.000'), (100000000, '100.000.000'), (150000000, '150.000.000'), (200000000, '200.000.000'), (300000000, '300.000.000'), (500000000, '500.000.000'), (1000000000, '1.000.000.000'), (5000000000, '5.000.000.000'), (10000000000, '10.000.000.000'), (15000000000, '15.000.000.000'), (20000000000, '20.000.000.000'), (25000000000, '25.000.000.000'), (30000000000, '30.000.000.000'), (35000000000, '35.000.000.000'), (40000000000, '40.000.000.000'), (45000000000, '45.000.000.000'), (50000000000, '50.000.000.000'), ('', '(không có)')], decimal_places=0, max_digits=15, null=True, verbose_name='Giá cao nhất'),
        ),
        migrations.AlterField(
            model_name='seoproduct',
            name='min_price',
            field=models.DecimalField(blank=True, choices=[(0, '0'), (500000, '500.000'), (1000000, '1.000.000'), (3000000, '3.000.000'), (5000000, '5.000.000'), (10000000, '10.000.000'), (30000000, '30.000.000'), (50000000, '50.000.000'), (80000000, '80.000.000'), (100000000, '100.000.000'), (150000000, '150.000.000'), (200000000, '200.000.000'), (300000000, '300.000.000'), (500000000, '500.000.000'), (1000000000, '1.000.000.000')], decimal_places=0, max_digits=15, null=True, verbose_name='Giá thấp nhất'),
        ),
        migrations.AlterField(
            model_name='seoproduct',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
    ]
