# Generated by Django 5.0.1 on 2024-01-27 13:51

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import sims.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimStore',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('f', models.CharField(max_length=15, null=True)),
                ('f0', models.IntegerField(null=True)),
                ('f1', models.IntegerField(null=True)),
                ('f2', models.IntegerField(null=True)),
                ('f3', models.IntegerField(null=True)),
                ('f4', models.IntegerField(null=True)),
                ('f5', models.IntegerField(null=True)),
                ('f6', models.IntegerField(null=True)),
                ('f7', models.IntegerField(null=True)),
                ('f8', models.IntegerField(null=True)),
                ('f9', models.IntegerField(null=True)),
                ('pb', models.IntegerField(null=True)),
                ('pn', models.IntegerField(null=True)),
                ('t', models.IntegerField(choices=[(1, 'viettel'), (2, 'vinaphone'), (3, 'mobifone'), (4, 'vietnamobile'), (5, 'gmobile'), (7, 'mayban'), (8, 'itelecom')], null=True)),
                ('d', models.BooleanField(default=False)),
                ('c2', models.IntegerField(choices=[(67, 'Sim Lặp kép'), (68, 'Sim Tứ quý'), (70, 'Sim Ông địa'), (71, 'Sim Đôi'), (72, 'Sim Thần tài'), (73, 'Sim Lộc phát'), (74, 'Sim Taxi'), (76, 'Sim Dễ nhớ'), (77, 'Sim Năm sinh'), (78, 'Sim Số độc'), (79, 'Sim Gánh đảo'), (80, 'Sim Tam hoa'), (81, 'Sim Tiến lên'), (82, 'Sim VIP'), (84, 'Sim tự chọn'), (86, 'Số máy bàn'), (99, 'Sim Ngũ Quý'), (100, 'Sim Lục Quý'), (102, 'Tam hoa kép'), (103, 'Sim Tứ Quý Giữa'), (104, 'Sim Ngũ Quý Giữa'), (105, 'Sim Lục Quý Giữa'), (106, 'Sim Đầu cổ'), (110, 'Sim hợp mệnh Thủy'), (111, 'Sim hợp mệnh Hỏa'), (112, 'Sim hợp mệnh Mộc'), (113, 'Sim hợp mệnh Thổ'), (114, 'Sim hợp mệnh Kim'), (115, 'Sim Đại Cát'), (116, 'Sim Cát'), (117, 'Sim Bình'), (118, 'Sim Hung'), (119, 'Sim Đại Hung'), (120, 'Sim Kép'), (121, 'Sim Kép 3'), (122, 'Sim Kép 4'), (123, 'Sim Lặp'), (124, 'Sim Lặp 3'), (125, 'Sim Lặp 4'), (126, 'Sim Taxi Lặp 3'), (127, 'Sim Taxi Lặp 2'), (128, 'Sim Taxi Lặp 4'), (200, 'Sim trả góp')], null=True)),
                ('c', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(67, 'Sim Lặp kép'), (68, 'Sim Tứ quý'), (70, 'Sim Ông địa'), (71, 'Sim Đôi'), (72, 'Sim Thần tài'), (73, 'Sim Lộc phát'), (74, 'Sim Taxi'), (76, 'Sim Dễ nhớ'), (77, 'Sim Năm sinh'), (78, 'Sim Số độc'), (79, 'Sim Gánh đảo'), (80, 'Sim Tam hoa'), (81, 'Sim Tiến lên'), (82, 'Sim VIP'), (84, 'Sim tự chọn'), (86, 'Số máy bàn'), (99, 'Sim Ngũ Quý'), (100, 'Sim Lục Quý'), (102, 'Tam hoa kép'), (103, 'Sim Tứ Quý Giữa'), (104, 'Sim Ngũ Quý Giữa'), (105, 'Sim Lục Quý Giữa'), (106, 'Sim Đầu cổ'), (110, 'Sim hợp mệnh Thủy'), (111, 'Sim hợp mệnh Hỏa'), (112, 'Sim hợp mệnh Mộc'), (113, 'Sim hợp mệnh Thổ'), (114, 'Sim hợp mệnh Kim'), (115, 'Sim Đại Cát'), (116, 'Sim Cát'), (117, 'Sim Bình'), (118, 'Sim Hung'), (119, 'Sim Đại Hung'), (120, 'Sim Kép'), (121, 'Sim Kép 3'), (122, 'Sim Kép 4'), (123, 'Sim Lặp'), (124, 'Sim Lặp 3'), (125, 'Sim Lặp 4'), (126, 'Sim Taxi Lặp 3'), (127, 'Sim Taxi Lặp 2'), (128, 'Sim Taxi Lặp 4'), (200, 'Sim trả góp')]), default=list, size=None)),
                ('h', models.BooleanField(default=False)),
                ('tt', models.IntegerField(choices=[(1, 'Trả trước'), (2, 'Trả sau')], null=True)),
                ('k', models.CharField(null=True)),
                ('ip', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('it', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('note', models.CharField(null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SimOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=sims.models.SimOrder.generate_unique_code, editable=False, max_length=20, unique=True)),
                ('sim', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(null=True)),
                ('other_option', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Mới đặt'), (2, 'Đang giao dịch'), (3, 'Hoàn tất'), (4, 'Hủy')], default=1, null=True)),
                ('order_type', models.IntegerField(choices=[(1, 'Đơn thường'), (2, 'Yêu cầu'), (3, 'Đơn tặng')], default=1, null=True)),
                ('sale_notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.CharField(default=sims.models.SimOrder.default_created_at, max_length=20)),
                ('updatedAt', models.CharField(default=sims.models.SimOrder.default_created_at, max_length=20)),
                ('source_text', models.CharField(max_length=50, null=True)),
                ('sale_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
