# Generated by Django 5.0.1 on 2024-02-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='sale_notes',
            field=models.JSONField(default=dict),
        ),
    ]
