# Generated by Django 5.0.1 on 2024-02-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0005_rename_viewed_simorder_pushed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='order_type',
            field=models.IntegerField(choices=[(1, 'Đơn thường'), (2, 'Yêu cầu'), (3, 'Đơn tặng'), (4, 'Đơn trả góp')], default=1, null=True),
        ),
    ]
