# Generated by Django 5.0.2 on 2024-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_alter_simorder_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simorder',
            name='store_type',
            field=models.IntegerField(default=1, help_text='xác định số được đặt từ appsim hay từ kho sim'),
            preserve_default=False,
        ),
    ]
