# Generated by Django 5.0.2 on 2024-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0007_simorder_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simorder',
            name='attributes',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Mới đặt'), (2, 'Đang giao dịch'), (3, 'Hoàn tất'), (4, 'Thanh toán'), (5, 'Hủy')], default=1, null=True),
        ),
    ]
