# Generated by Django 5.0.2 on 2024-02-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0008_simorder_attributes_alter_simorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='simorder',
            name='browse_history',
            field=models.TextField(blank=True, default={}, null=True),
        ),
    ]
