# Generated by Django 5.0.2 on 2024-02-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0010_alter_simorder_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
