# Generated by Django 5.0.2 on 2024-02-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0011_alter_simorder_attributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simorder',
            old_name='price',
            new_name='amount',
        ),
    ]
