# Generated by Django 5.0.2 on 2024-02-29 03:56

import django.db.models.deletion
import sims.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0012_rename_price_simorder_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='code',
            field=models.CharField(default=sims.models.SimOrder.generate_unique_code, editable=False, max_length=20, unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên KH'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='order_type',
            field=models.IntegerField(choices=[(1, 'Đơn thường'), (2, 'Yêu cầu'), (3, 'Đơn tặng'), (4, 'Đơn trả góp')], default=1, null=True, verbose_name='Kiểu đơn'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='sale_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Phụ trách'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='source_text',
            field=models.CharField(max_length=50, null=True, verbose_name='Nguồn'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='t',
            field=models.IntegerField(choices=[(1, 'viettel'), (2, 'vinaphone'), (3, 'mobifone'), (4, 'vietnamobile'), (5, 'gmobile'), (7, 'mayban'), (8, 'itelecom'), (9, 'wintel')], null=True),
        ),
    ]
