# Generated by Django 5.0.2 on 2024-03-03 03:17

import sims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0013_alter_simorder_code_alter_simorder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='address',
            field=models.TextField(null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='createdAt',
            field=models.CharField(default=sims.models.SimOrder.default_created_at, max_length=20, verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='pushed',
            field=models.BooleanField(default=False, verbose_name='Webhook'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Mới đặt'), (2, 'Đang giao dịch'), (3, 'Hoàn tất'), (4, 'Thanh toán'), (5, 'Hủy')], default=1, null=True, verbose_name='Trạng thái'),
        ),
    ]
