# Generated by Django 5.0.2 on 2024-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0014_alter_simorder_address_alter_simorder_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitual_names', models.CharField(max_length=100)),
                ('vitual_address', models.TextField()),
                ('vitual_sims', models.CharField(max_length=20)),
                ('vitual_times', models.CharField(max_length=20)),
            ],
        ),
    ]
