# Generated by Django 5.0.2 on 2024-03-07 17:23

import django.db.models.deletion
import sims.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0015_salealert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simorder',
            name='category',
            field=models.IntegerField(choices=[(67, 'Sim Lặp kép'), (68, 'Sim Tứ quý'), (70, 'Sim Ông địa'), (71, 'Sim Đôi'), (72, 'Sim Thần tài'), (73, 'Sim Lộc phát'), (74, 'Sim Taxi'), (76, 'Sim Dễ nhớ'), (77, 'Sim Năm sinh'), (78, 'Sim Số độc'), (79, 'Sim Gánh đảo'), (80, 'Sim Tam hoa'), (81, 'Sim Tiến lên'), (82, 'Sim VIP'), (84, 'Sim tự chọn'), (86, 'Số máy bàn'), (99, 'Sim Ngũ Quý'), (100, 'Sim Lục Quý'), (102, 'Tam hoa kép'), (103, 'Sim Tứ Quý Giữa'), (104, 'Sim Ngũ Quý Giữa'), (105, 'Sim Lục Quý Giữa'), (106, 'Sim Đầu cổ'), (110, 'Sim hợp mệnh Thủy'), (111, 'Sim hợp mệnh Hỏa'), (112, 'Sim hợp mệnh Mộc'), (113, 'Sim hợp mệnh Thổ'), (114, 'Sim hợp mệnh Kim'), (115, 'Sim Đại Cát'), (116, 'Sim Cát'), (117, 'Sim Bình'), (118, 'Sim Hung'), (119, 'Sim Đại Hung'), (120, 'Sim Kép'), (121, 'Sim Kép 3'), (122, 'Sim Kép 4'), (123, 'Sim Lặp'), (124, 'Sim Lặp 3'), (125, 'Sim Lặp 4'), (126, 'Sim Taxi Lặp 3'), (127, 'Sim Taxi Lặp 2'), (128, 'Sim Taxi Lặp 4'), (200, 'Sim trả góp')], null=True, verbose_name='Loại sim'),
        ),
        migrations.AddField(
            model_name='simorder',
            name='network',
            field=models.IntegerField(choices=[(1, 'viettel'), (2, 'vinaphone'), (3, 'mobifone'), (4, 'vietnamobile'), (5, 'gmobile'), (7, 'mayban'), (8, 'itelecom'), (9, 'wintel')], null=True, verbose_name='Nhà mạng'),
        ),
        migrations.AddField(
            model_name='simorder',
            name='reason_text',
            field=models.CharField(blank=True, null=True, verbose_name='Lý do huỷ đơn'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Gía bán lẻ'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='code',
            field=models.CharField(default=sims.models.SimOrder.generate_unique_code, editable=False, max_length=20, unique=True, verbose_name='Mã đơn hàng'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='createdAt',
            field=models.CharField(default=sims.models.SimOrder.default_created_at, max_length=20, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='order_type',
            field=models.IntegerField(choices=[(1, 'Đơn thường'), (2, 'Yêu cầu'), (3, 'Đơn tặng'), (4, 'Đơn trả góp')], default=1, null=True, verbose_name='Loại đơn'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='other_option',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú đơn hàng'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='sale_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='sim',
            field=models.CharField(max_length=20, verbose_name='Số sim đặt mua'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='source_text',
            field=models.CharField(max_length=50, null=True, verbose_name='Nguồn đơn'),
        ),
    ]
