# Generated by Django 5.0.2 on 2024-03-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0016_simorder_category_simorder_network_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simorder',
            old_name='category',
            new_name='c2',
        ),
        migrations.RenameField(
            model_name='simorder',
            old_name='network',
            new_name='telco_id',
        ),
        migrations.AlterField(
            model_name='simorder',
            name='reason_text',
            field=models.CharField(blank=True, null=True, verbose_name='Lý do'),
        ),
    ]
