# Generated by Django 5.0.2 on 2024-03-11 04:23

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0017_rename_category_simorder_c2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simstore',
            name='c',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(67, 'Sim Lặp kép'), (68, 'Sim Tứ quý'), (70, 'Sim Ông địa'), (71, 'Sim Đôi'), (72, 'Sim Thần tài'), (73, 'Sim Lộc phát'), (74, 'Sim Taxi'), (76, 'Sim Dễ nhớ'), (77, 'Sim Năm sinh'), (78, 'Sim Số độc'), (79, 'Sim Gánh đảo'), (80, 'Sim Tam hoa'), (81, 'Sim Tiến lên'), (82, 'Sim VIP'), (84, 'Sim tự chọn'), (86, 'Số máy bàn'), (99, 'Sim Ngũ Quý'), (100, 'Sim Lục Quý'), (102, 'Tam hoa kép'), (103, 'Sim Tứ Quý Giữa'), (104, 'Sim Ngũ Quý Giữa'), (105, 'Sim Lục Quý Giữa'), (106, 'Sim Đầu cổ'), (110, 'Sim hợp mệnh Thủy'), (111, 'Sim hợp mệnh Hỏa'), (112, 'Sim hợp mệnh Mộc'), (113, 'Sim hợp mệnh Thổ'), (114, 'Sim hợp mệnh Kim'), (115, 'Sim Đại Cát'), (116, 'Sim Cát'), (117, 'Sim Bình'), (118, 'Sim Hung'), (119, 'Sim Đại Hung'), (120, 'Sim Kép'), (121, 'Sim Kép 3'), (122, 'Sim Kép 4'), (123, 'Sim Lặp'), (124, 'Sim Lặp 3'), (125, 'Sim Lặp 4'), (126, 'Sim Taxi Lặp 3'), (127, 'Sim Taxi Lặp 2'), (128, 'Sim Taxi Lặp 4'), (200, 'Sim trả góp')]), default=list, size=None, verbose_name='Loại sim'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='c2',
            field=models.IntegerField(choices=[(67, 'Sim Lặp kép'), (68, 'Sim Tứ quý'), (70, 'Sim Ông địa'), (71, 'Sim Đôi'), (72, 'Sim Thần tài'), (73, 'Sim Lộc phát'), (74, 'Sim Taxi'), (76, 'Sim Dễ nhớ'), (77, 'Sim Năm sinh'), (78, 'Sim Số độc'), (79, 'Sim Gánh đảo'), (80, 'Sim Tam hoa'), (81, 'Sim Tiến lên'), (82, 'Sim VIP'), (84, 'Sim tự chọn'), (86, 'Số máy bàn'), (99, 'Sim Ngũ Quý'), (100, 'Sim Lục Quý'), (102, 'Tam hoa kép'), (103, 'Sim Tứ Quý Giữa'), (104, 'Sim Ngũ Quý Giữa'), (105, 'Sim Lục Quý Giữa'), (106, 'Sim Đầu cổ'), (110, 'Sim hợp mệnh Thủy'), (111, 'Sim hợp mệnh Hỏa'), (112, 'Sim hợp mệnh Mộc'), (113, 'Sim hợp mệnh Thổ'), (114, 'Sim hợp mệnh Kim'), (115, 'Sim Đại Cát'), (116, 'Sim Cát'), (117, 'Sim Bình'), (118, 'Sim Hung'), (119, 'Sim Đại Hung'), (120, 'Sim Kép'), (121, 'Sim Kép 3'), (122, 'Sim Kép 4'), (123, 'Sim Lặp'), (124, 'Sim Lặp 3'), (125, 'Sim Lặp 4'), (126, 'Sim Taxi Lặp 3'), (127, 'Sim Taxi Lặp 2'), (128, 'Sim Taxi Lặp 4'), (200, 'Sim trả góp')], null=True, verbose_name='Loại sim chính'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='f',
            field=models.CharField(max_length=15, null=True, verbose_name='Số sim'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='h',
            field=models.BooleanField(default=False, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='ip',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None, verbose_name='Lãi suất trả góp'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='it',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None, verbose_name='Thời hạn trả góp'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='k',
            field=models.CharField(null=True, verbose_name='Gói cước'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='note',
            field=models.CharField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='pb',
            field=models.BigIntegerField(null=True, verbose_name='Giá bán'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='pn',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian update'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='t',
            field=models.IntegerField(choices=[(1, 'viettel'), (2, 'vinaphone'), (3, 'mobifone'), (4, 'vietnamobile'), (5, 'gmobile'), (7, 'mayban'), (8, 'itelecom'), (9, 'wintel')], null=True, verbose_name='Nhà mạng'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='tt',
            field=models.IntegerField(choices=[(1, 'Trả trước'), (2, 'Trả sau')], null=True, verbose_name='Loại mạng'),
        ),
    ]
