# Generated by Django 4.2.11 on 2024-03-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0020_alter_simorder_createdat_alter_simorder_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simstore',
            name='h',
            field=models.BooleanField(default=False, verbose_name='Ẩn số sim khỏi web'),
        ),
        migrations.AlterField(
            model_name='simstore',
            name='note',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Comment giữ số'),
        ),
    ]
