# Generated by Django 4.2.11 on 2024-03-22 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0020_alter_simorder_createdat_alter_simorder_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simstore',
            name='h',
            field=models.BooleanField(default=False, verbose_name='Ẩn số sim khỏi web'),
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('amount_thu', models.BigIntegerField(null=True)),
                ('amount_chi', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('transfer_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày chuyển')),
                ('status', models.IntegerField(choices=[(1, 'Tạm'), (2, 'Thanh toán')], default=1, null=True, verbose_name='Trạng thái')),
                ('type', models.IntegerField(choices=[(1, 'Thợ'), (2, 'KH')], default=1, null=True, verbose_name='Loại')),
                ('sim_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.simorder')),
            ],
        ),
    ]
