# Generated by Django 4.2.11 on 2024-03-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0020_alter_simorder_createdat_alter_simorder_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simstore',
            name='h',
            field=models.BooleanField(default=False, verbose_name='Ẩn số sim khỏi web'),
        ),
    ]
