# Generated by Django 4.2.11 on 2024-03-29 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0022_remove_accountreceivable_id_accountreceivable_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivable',
            name='created_at2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tạo 2'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='amount_chi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gốc còn lại'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='amount_thu',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Số tiền thu'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='transfer_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày thanh toán'),
        ),
    ]
