# Generated by Django 4.2.11 on 2024-03-29 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0023_accountreceivable_created_at2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountreceivable',
            name='created_at2',
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='created_userpay',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày thanh toán'),
        ),
    ]
