# Generated by Django 4.2.11 on 2024-03-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0021_alter_simstore_h'),
        ('sims', '0025_accountreceivable_method_pay_and_more'),
    ]

    operations = [
    ]
