# Generated by Django 4.2.11 on 2024-04-01 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0021_alter_simstore_h_alter_simstore_note'),
        ('sims', '0026_merge_20240330_0321'),
    ]

    operations = [
    ]
