# Generated by Django 4.2.11 on 2024-04-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0027_merge_20240401_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountreceivable',
            old_name='amount_thu',
            new_name='amount_payment',
        ),
        migrations.RenameField(
            model_name='accountreceivable',
            old_name='amount_chi',
            new_name='amount_remaining',
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='method_pay',
            field=models.IntegerField(choices=[(1, 'Tiền mặt'), (2, 'Chuyển khoản')], default=1, null=True, verbose_name='Hình thức thanh toán'),
        ),
    ]
