# Generated by Django 4.2.11 on 2024-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0029_simstore_t_detect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá bán'),
        ),
    ]
