# Generated by Django 4.2.11 on 2024-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0030_alter_simorder_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='simorder',
            name='name_deliver',
            field=models.CharField(blank=True, null=True, verbose_name='Tên người giao'),
        ),
        migrations.AddField(
            model_name='simorder',
            name='phone_deliver',
            field=models.CharField(blank=True, null=True, verbose_name='Số điện thoại người giao'),
        ),
        migrations.AddField(
            model_name='simorder',
            name='transport',
            field=models.IntegerField(choices=[(0, 'Tự giao dịch'), (1, 'Giao dịch hộ'), (2, 'COD')], null=True, verbose_name='Giao vận'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='amount_payment',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='method_pay',
            field=models.IntegerField(choices=[(1, 'Tiền mặt'), (2, 'Chuyển khoản')], default=1, null=True, verbose_name='Kiểu Thanh toán'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='status',
            field=models.IntegerField(choices=[(1, 'Tạm tính'), (2, 'Đã thanh toán')], default=1, null=True, verbose_name='Trạng thái'),
        ),
    ]
