# Generated by Django 4.2.11 on 2024-04-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0032_remove_accountreceivable_transfer_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simstore',
            old_name='note',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='simstore',
            name='note',
            field=models.CharField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
