# Generated by Django 4.2.11 on 2024-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0033_simstore_comment_alter_simstore_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='simorder',
            name='pay_kh_status',
            field=models.IntegerField(choices=[(0, 'Đã thanh toán'), (1, 'Chưa thanh toán'), (2, 'Huỷ thanh toán')], null=True, verbose_name='Trạng thái thanh toán'),
        ),
    ]
