# Generated by Django 4.2.11 on 2024-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0034_simorder_status_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivable',
            name='attach_file',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='article'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='comment',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='status_pay',
            field=models.IntegerField(choices=[(0, 'Chưa thanh toán'), (1, 'Đang thanh toán'), (2, 'Đã thanh toán')], null=True, verbose_name='Trạng thái thanh toán'),
        ),
    ]
