# Generated by Django 4.2.11 on 2024-04-11 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0035_accountreceivable_attach_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreceivable',
            name='attach_file',
            field=models.ImageField(blank=True, null=True, upload_to='account_receivable'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='created_userpay',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày TT'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='method_pay',
            field=models.IntegerField(choices=[(1, 'Tiền mặt'), (2, 'Chuyển khoản')], default=1, null=True, verbose_name='Kiểu TT'),
        ),
    ]
