# Generated by Django 4.2.11 on 2024-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0036_alter_accountreceivable_attach_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleAlert',
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='amount_interest',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tiền lãi'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='attach_file',
            field=models.ImageField(blank=True, null=True, upload_to='account_receivable', verbose_name='Đính kèm'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='name_deliver',
            field=models.CharField(blank=True, null=True, verbose_name='Người giao'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='phone_deliver',
            field=models.CharField(blank=True, null=True, verbose_name='SĐT người giao'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='pay_kh_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Chưa thanh toán'), (1, 'Đang thanh toán'), (2, 'Đã thanh toán')], null=True, verbose_name='Trạng thái TT'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='transport',
            field=models.IntegerField(blank=True, choices=[(0, 'Tự giao dịch'), (1, 'Giao dịch hộ'), (2, 'COD')], null=True, verbose_name='Giao vận'),
        ),
    ]
