# Generated by Django 4.2.11 on 2024-04-12 11:06

from django.db import migrations, models

def update_installment_type(apps, schema_editor):
    SimStore = apps.get_model('sims', 'SimStore')
    SimStore.objects.filter(iir__isnull=False).update(installment_type=1)

class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0037_delete_salealert_accountreceivable_amount_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simstore',
            name='iir_vnd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simstore',
            name='installment_type',
            field=models.IntegerField(blank=True, choices=[(1, '% / tháng'), (2, 'đồng / triệu')], null=True, verbose_name='Loại trả góp'),
        ),
        migrations.RunPython(update_installment_type),
    ]
