# Generated by Django 4.2.11 on 2024-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0037_delete_salealert_accountreceivable_amount_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivable',
            name='amount_interest_temp',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Lãi tạm tính'),
        ),
    ]
