# Generated by Django 4.2.11 on 2024-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0038_accountreceivable_amount_interest_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='store_type',
            field=models.IntegerField(choices=[(2, 'Kho App Sim'), (3, 'Kho SIM')], help_text='Xác định số được đặt từ appsim hay từ kho sim', verbose_name='Kho nguồn'),
        ),
    ]
