# Generated by Django 4.2.11 on 2024-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0039_alter_simorder_store_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simorder',
            name='status_pay',
        ),
        migrations.AddField(
            model_name='simorder',
            name='pay_tho_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Chưa thanh toán'), (1, 'Đang thanh toán'), (2, 'Đã thanh toán')], null=True, verbose_name='Trạng thái TT Thợ'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='pay_kh_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Chưa thanh toán'), (1, 'Đang thanh toán'), (2, 'Đã thanh toán')], null=True, verbose_name='Trạng thái TT KH'),
        ),
    ]
