# Generated by Django 4.2.11 on 2024-04-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0038_simstore_iir_vnd_simstore_installment_type'),
        ('sims', '0040_remove_simorder_status_pay_simorder_pay_tho_status_and_more'),
    ]

    operations = [
    ]
