# Generated by Django 4.2.11 on 2024-04-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0041_merge_20240412_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simstore',
            name='iir_vnd',
        ),
    ]
