# Generated by Django 4.2.11 on 2024-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0042_remove_simstore_iir_vnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
    ]
