# Generated by Django 4.2.11 on 2024-04-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0044_simorder_costs_simorder_note_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Mới đặt'), (2, 'Đang xử lý'), (3, 'Đang giao'), (4, 'Đã giao'), (5, 'Hoàn tất'), (6, 'Thất bại'), (7, 'Hủy')], default=1, null=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='transport',
            field=models.IntegerField(blank=True, choices=[(0, 'Tự giao dịch'), (1, 'Giao dịch hộ'), (2, 'COD'), (3, 'Cấp lại sim')], null=True, verbose_name='Giao vận'),
        ),
    ]
