# Generated by Django 4.2.11 on 2024-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0045_alter_simorder_status_alter_simorder_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='other_option',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Ghi chú đơn hàng'),
        ),
    ]
