# Generated by Django 4.2.11 on 2024-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0046_alter_simorder_address_alter_simorder_other_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Mới đặt'), (2, 'Đang xử lý'), (3, 'Đang giao'), (4, 'Đã giao'), (5, 'Hoàn tất'), (6, 'Thất bại'), (7, 'Hủy')], default=1, help_text='Trạng thái vận chuyển', null=True, verbose_name='Trạng thái VC'),
        ),
    ]
